-- Execute uma vez no SQL Editor se a tabela products já existir.
alter table products add column if not exists store_id bigint generated by default as identity;
alter table products add column if not exists category_label text not null default 'Geral';
create unique index if not exists products_store_id_idx on products(store_id);
alter table products enable row level security;

-- O catálogo público é lido pelo servidor usando a service role.
-- Não crie políticas de escrita para clientes anônimos.
