-- 3D Store - modelo inicial de produção para PostgreSQL/Supabase.
-- Execute no SQL Editor do Supabase antes de habilitar o modo persistente.

create extension if not exists "pgcrypto";

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique
);

create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  store_id bigint generated by default as identity unique,
  title text not null,
  slug text not null unique,
  description text,
  price_cents integer not null check (price_cents >= 0),
  image_url text,
  category_id uuid references categories(id) on delete set null,
  category_label text not null default 'Geral',
  stock integer not null default 0 check (stock >= 0),
  weight_grams integer not null default 300 check (weight_grams > 0),
  length_cm numeric(8,2) not null default 20,
  width_cm numeric(8,2) not null default 20,
  height_cm numeric(8,2) not null default 10,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  recipient text not null,
  postal_code text not null,
  street text not null,
  number text not null,
  complement text,
  neighborhood text not null,
  city text not null,
  state char(2) not null,
  created_at timestamptz not null default now()
);

create type order_status as enum ('pending_payment', 'paid', 'processing', 'shipped', 'delivered', 'cancelled');

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  status order_status not null default 'pending_payment',
  subtotal_cents integer not null check (subtotal_cents >= 0),
  shipping_cents integer not null default 0 check (shipping_cents >= 0),
  total_cents integer not null check (total_cents >= 0),
  shipping_method text not null,
  shipping_estimate_days integer not null,
  address_snapshot jsonb not null,
  payment_provider text,
  payment_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references orders(id) on delete cascade,
  product_id uuid references products(id) on delete set null,
  title_snapshot text not null,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0)
);

create index if not exists products_active_idx on products(active);
create index if not exists orders_user_idx on orders(user_id, created_at desc);
create index if not exists order_items_order_idx on order_items(order_id);

alter table profiles enable row level security;
alter table products enable row level security;
alter table addresses enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

drop policy if exists "users read own profile" on profiles;
create policy "users read own profile" on profiles for select using (auth.uid() = id);
drop policy if exists "users manage own addresses" on addresses;
create policy "users manage own addresses" on addresses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "users read own orders" on orders;
create policy "users read own orders" on orders for select using (auth.uid() = user_id);
drop policy if exists "users read own order items" on order_items;
create policy "users read own order items" on order_items for select using (exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid()));
